### ISSUE TITLE
Definir el modelo ER/NoSQL

### ISSUE THREAD

**Issue by MauroGonzalez51** [ISCOUTB/AG-Analysis-ICFES-Backend#1]

**Comment by MauroGonzalez51** [comment]
Modelos ER definidos para cada parte de la aplicacion.
Frontend: Creacion de un modelo ER (Basico) para la autenticacion de usuarios en usando Postgresql, junto con Prisma como ORM para manejar los datos.

Backend: Creacion de un modelo orientado para ser utilizado con el lenguaje de consultas GraphQL.  El modelo fue creado usando el ORM integrado de Django

**Comment by jairoserrano** [comment]
OK
