### ISSUE TITLE
Documentacion API (backend)

### ISSUE THREAD

**Issue by MauroGonzalez51** [ISCOUTB/AG-Analysis-ICFES-Backend#11]

**Comment by AaronDaliLF** [comment]
Se indica la documentación de la API  basado en los esquemas generados en GraphQl para el backend. Se enfatiza en el método post ya que solamente se requieren de consultas de los datos, sin modificarlos ni sobreescribirlos, es decir, solamente se realizan operaciones de lectura. Se encuentra en la siguiente ruta del repo: AG-Analysis-ICFES-Backend/docs/Backend api.yaml

**Comment by jairoserrano** [comment]
adelante
