### ISSUE TITLE
Data Analysis

### ISSUE THREAD

**Issue by MauroGonzalez51** [ISCOUTB/AG-Analysis-ICFES-Backend#12]

**Comment by MauroGonzalez51** [comment]
Añadido un script en apps/backend/data/clean.ipynb que se encarga de eliminar todos los valores nulos de ambos archivos. Lo que resulta en una reducción significativa de los datos.
 
 Este último escalara indefinidamente siempre y cuando el schema de los datos no cambie, aunque el limitante va a ser la memoria de la máquina, ya que se necesitara en algún punto, cargar todo el dataframe en memoria, lo que puede resultar en un uso de más de 8 GB de RAM.
 
 En todo caso, los archivos se exportan para luego trabajar con la porción de los datos que nos interesan.

**Comment by MauroGonzalez51** [comment]
Se volvió otra vez a usar un script de django, concretamente llamado seed_db. De esta manera al tomar un acercamiento mas funcional, se puede liberar de la memoria el dataframe cuando ya se haya leído/exportado y simplemente almacenar el nombre (como UUID) cuando se requiera hacer otra operación.

Por lo que se opta mas por un on_demand al momento de trabajar con los archivos.

**Comment by MauroGonzalez51** [comment]
En el script se avanzó bastante, solamente que se trabaja con el notebook de lado para ir haciendo testeos, ya que sigue siendo más cómodo.

Aqui 956651143df05bd53d278d82afc18a75f061a24a se puede ver que en si es funcional, pero que realmente hace demasiadas consultas a la base de datos (posiblemente con una complejidad n^3).

Lo siguiente a intentar es tomando todos los valores unicos y crear todos los objetos a la vez para ir modificandolos on demand

**Comment by MauroGonzalez51** [comment]
170fdbf01c7ca7a433082cdbe944ab783d6f393d 
Se utilizo un enfoque por "batch",  de 10k datos cada uno, en los que se van insertando a db, ademas de hacer el proceso en multithread

**Comment by jairoserrano** [comment]
adelante, buena aproximación para el trabajo de datos en bloque
