### ISSUE TITLE
Infraestructura de la API (backend)

### ISSUE THREAD

**Issue by MauroGonzalez51** [ISCOUTB/AG-Analysis-ICFES-Backend#2]

**Comment by MauroGonzalez51** [comment]
Para la infraestructura de la API, se decidió utilizar GraphQL debido a la complejidad de las consultas. Con un modelo REST, sería necesario realizar múltiples consultas para obtener todos los datos requeridos, lo que podría causar retrasos y afectar la experiencia del usuario final.

Por este motivo, se optó por una estructura GraphQL, que permite crear consultas más complejas y ofrece varias ventajas adicionales:

- Flexibilidad en las Consultas: Los clientes pueden solicitar exactamente los datos que necesitan, reduciendo la cantidad de datos transferidos y mejorando la eficiencia.
- Reducción de Solicitudes: GraphQL permite obtener todos los datos necesarios en una sola solicitud, reduciendo la latencia y mejorando la velocidad de respuesta.

**Comment by jairoserrano** [comment]
adelante
