### ISSUE TITLE
(frontend) (UI) design pages |pricing| |about| |contact|

### ISSUE THREAD

**Issue by MauroGonzalez51** [ISCOUTB/AG-Analysis-ICFES-Backend#21]

**Comment by JuanJimenezGuardo** [comment]
mockups about

![mockups about](https://github.com/user-attachments/assets/d668da83-b7b5-441f-baf4-643d4e13d56d)

mockups contact

![mockups contact](https://github.com/user-attachments/assets/8981b3e9-2a3f-4c65-bf94-bc2094b52e3f)

mockups pricing

![mockups pricing](https://github.com/user-attachments/assets/3dd1a461-4169-486f-8ea6-fd4213bdf78b)
