### ISSUE TITLE
Tipos de modelos de las bases de datos a utilizar

### ISSUE THREAD

**Issue by AaronDaliLF** [ISCOUTB/AG-Analysis-ICFES-Backend#3]

**Comment by AaronDaliLF** [comment]
Dado que el modelado de la datos realizados por medio del diagrama de entidad relación nos permite vincular las diferentes entidades por medio de identificadores únicos y de la misma manera asociar los atributos de una entidad con los de otra es posible emplear bases de datos con estas características, es decir,  bases de datos relacionales.

Para este caso, se empleará el gestor de bases de datos PostgreSQL. Esta elección se basa en el volumen de datos a manejar. Se recuerda que en este caso se registrarán y analizarán los datos asociados a las pruebas estandarizadas del Estado (ICFES), esto incluye entidades como estudiantes, departamentos, municipios, información por colegio y universidad.

**Comment by jairoserrano** [comment]
ok
