### ISSUE TITLE
Mockups para la UI

### ISSUE THREAD

**Issue by MauroGonzalez51** [ISCOUTB/AG-Analysis-ICFES-Backend#4]

**Comment by JuanJimenezGuardo** [comment]
Added Mockup Menu, Mockup Login, Mockup Dark Login
![jjjjj233333](https://github.com/user-attachments/assets/5ec4cdc4-fb04-4692-acef-be6bd5b9cbab)
![jjjj22222](https://github.com/user-attachments/assets/bec36b7e-c756-4662-8c87-1a151ae0e757)
![rvrvvrdvrvdrvdr](https://github.com/user-attachments/assets/4d7b397a-5114-4ae6-bd94-873f6e198abd)

**Comment by JorgeAndres-GitHub** [comment]
@
![REGISTRO-PAGE](https://github.com/user-attachments/assets/0cdf3724-1992-4c91-a5aa-f28bd3168180)

**Comment by JorgeAndres-GitHub** [comment]
![image](https://github.com/user-attachments/assets/f5900ede-1ea2-484f-b4bc-cdc727bd2919)

**Comment by jairoserrano** [comment]
ok
